service: ${file(package.json):name}
provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:PROFILE, 'default'}
  region: ${env:REGION, 'eu-west-2'}
  stage: ${env:STAGE, 'dev'}
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:3000
        - https://d14m0uqec29uyj.cloudfront.net
    authorizers:
      spotifyAuthorizer:
        type: request
        enableSimpleResponses: true
        identitySource: $request.header.Authorization
        functionName: spotifyAuthorizer
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}

plugins:
  - serverless-esbuild

functions:
  spotifyAuthorizer:
    handler: src/functions/authorizer.handler
  	
  getRecommendations:
    handler: src/functions/get-recommendations.GetRecommendations
    timeout: 30
    events:
      - httpApi:
          method: GET
          path: /recommendations
          authorizer:
            name: spotifyAuthorizer